### ISSUE TITLE
cf submit and cf watch don't detect contest and problem automatically

### ISSUE THREAD

**Issue by confusedman1** [cp-tools/cf-tool#13]
## Bug description
When I go to the problem subfolder of a parsed contest and type in `cf watch` or `cf submit` (when there is already a code file in the current directory), the contest/problem id isn't detected automatically and the response is `No problem id found` or `No contest id found` depending on the command.

## Steps to reproduce
1. Parse a contest, generate a code file in the problem subfolder.
2. Change directory to the problem subfolder, e.g -> `cd 1355/a/`
3. Try `cf watch` or `cf submit`

## Expected Behaviour
The contest/problem id is supposed to be detected automatically

## System Details
 - macOS Catalina

**Comment by Ahmad45123** [comment]
I have same issue here. Please fix asap.

**Comment by infalmo** [comment]
Can you give me the full path to the folder containing the contest/problem?
I can't reproduce it on ubuntu/arch linux

**Comment by Ahmad45123** [comment]
> Can you give me the full path to the folder containing the contest/problem?
> I can't reproduce it on ubuntu/arch linux

Err I'm using WSL ubuntu if it makes any difference.
The path is at /mnt/d/cppractice/contest/..

**Comment by infalmo** [comment]
Ah, lol. The value of `WSName` can't be empty.

Actually, this naming was introduced because when this tool is extended to other websites too, it becomes hard (if not impossible) to determine what website and problem the current folder is referring to, without the name of the website.

Thus, the path must be something like `/mnt/d/cppractice/<WSName>/contest/....`. `WSName` can be changed using `cf config`.

**Comment by Ahmad45123** [comment]
That worked ty.
